[/Script/EnhancedInput.EnhancedInputDeveloperSettings]
; 使用Enhanced Input System
bEnableDefaultMappingContexts=True

[/Script/Engine.InputSettings]
DefaultViewportMouseCaptureMode=CapturePermanently_IncludingInitialMouseDown
bCaptureMouseOnLaunch=True
DefaultViewportMouseLockMode=LockOnCapture
